export const DEFAULT_PLAYER_NAME = "Nova";

export const BOT_CALL_SIGN_POOL = [
  "Pulsar",
  "Nebula",
  "Quasar",
  "Vega",
  "Comet",
  "Zenith",
  "Eclipse",
  "Andromeda",
  "Cosmo",
  "Stellar",
  "Astra",
  "Photon",
  "Neutron",
  "Meteor",
  "Orion",
  "Lyra",
  "Sirius",
  "Altair",
  "Rigel",
  "Solstice",
  "Celeste",
  "Aurora",
  "Galatea",
  "Hyperion",
  "Io",
  "Juno",
  "Kepler",
  "Luna",
  "Mirage",
  "Nyx",
  "Oberon",
  "Perseus",
  "Rhea",
  "Selene",
  "Triton",
  "Umbra",
  "Vela",
  "Xenon",
  "Ymir",
  "Arcturus",
  "Bellatrix",
  "Cassiopeia",
  "Draco",
  "Elara",
  "Fomalhaut",
  "Gemini",
  "Helios",
  "Indus",
  "Janus",
  "Kuiper",
] as const;

export function getBotCallSign(botIndex: number): string {
  return BOT_CALL_SIGN_POOL[botIndex] ?? BOT_CALL_SIGN_POOL[botIndex % BOT_CALL_SIGN_POOL.length];
}
